
x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
services:
  sunshine:
    image: ghcr.io/lizardbyte/sunshine:v2026.228.232233-ubuntu-24.04
    restart: unless-stopped
    ipc: host
    ports: 
      - '47984-47990:47984-47990/tcp'
      - '48010:48010'
      - '47998-48000:47998-48000/udp'
    volumes:
      - '/mnt/Vault/Configuration/sunshine:/config'
      - '/mnt/Vault/Media/Games:/data/games'
    logging: *logging-config